accounts/urls.py
from django.urls import path
from . import views

#FOR AUTH APP
app_name = "accounts"

urlpatterns = [
    path("", views.index, name = "index"),
    path("signup", views.signup, name = "signup"),
    path("logout", views.signout, name = "signout"),
]

app/urls.py
from django.urls import path
from . import views

#FOR CORE APP
app_name = "scheduleapp"

urlpatterns = [
    path("", views.index, name = 'index'),
    path("profile/", views.index, name = "profile"),
    path("about/", views.about, name = "about"),
    path("add/", views.addingMenu, name = "adding"),
    path("add-student/", views.addStudent, name = "addStudent"),
    path("<int:year_id>", views.deleteStudent, name = "deleteStudent"),
    path("add-lesson/", views.addLesson, name = "addLesson"),
    path("add-teacher/", views.addTeacher, name = "addTeacher"),
    path("add-student/<int:year_id>/", views.viewStudents, name = "viewStudents"),
    path("search", views.search, name = "search")
]

schedule/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("schedule/", include('app.urls')),
    path("authentication/", include('accounts.urls')),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.

class User(AbstractUser):
    pass

app/models.py
from django.db import models
from accounts.models import User
from django.core.validators import MinValueValidator, MaxValueValidator

class DaysOfWeek(models.Model):
    name = models.CharField(verbose_name="name", max_length=10)
    
    def __str__(self):
        return f"{self.id} - {self.name}"
    
    class Meta:
        ordering = ('id',)

class Lesson(models.Model):
    title = models.CharField(max_length = 32)
    time = models.TimeField(blank=True , null= True)
    teacher = models.ForeignKey(User, on_delete = models.CASCADE, related_name = "teacher")
    cabinet = models.IntegerField(blank= True , null= True)
    day = models.ForeignKey(DaysOfWeek, on_delete= models.CASCADE ,related_name = "day", blank= True , null= True)

    def __str__(self):
        return f"{self.title} is teached by {self.teacher} on {self.time}"

    # class Meta:
    #     unique_together = ('teacher')
    
class Students(models.Model):
    group_year = models.IntegerField()
    group_title = models.CharField(max_length= 10)
    group_number = models.IntegerField()
    lessons = models.ManyToManyField(Lesson, blank=True)

    def __str__(self):
        return f"{self.group_year}{self.group_title}-{self.group_number}"

    class Meta:
        unique_together = ('group_year', 'group_title', 'group_number')

accounts/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.hashers import check_password
from django.contrib.auth.models import User
from django.contrib import messages
from django.urls import reverse
from django import forms

from .models import User

#APP FOR AUTH

class SignInForm(forms.Form):
    required_css_class = 'sign_in_form'
    name = forms.CharField(widget = forms.TextInput(attrs = {'class':'form_field username', 'required': 'True', 'placeholder':'Name'}),max_length=32,label = '', required=False)
    password = forms.CharField(widget = forms.PasswordInput(attrs = {'class':'form_field password', 'required': 'True', 'placeholder':'Password'}), required= False, label = '')
    
    class Meta:
        model = User

class SignUpForm(forms.Form):
    name = forms.CharField(widget = forms.TextInput(attrs = {'class':'form_field username', 'required': 'True', 'placeholder':'Name'}),max_length=32,label = '', required=False)
    password = forms.CharField(widget = forms.PasswordInput(attrs = {'class':'form_field password', 'required': 'True', 'placeholder':'Password'}), required= False, label = '')
    confirmPassword = forms.CharField(widget = forms.PasswordInput(attrs = {'class':'form_field password', 'required': 'True', 'placeholder':'Confirm Password'}), required= False, label = '')

    class Meta:
        model = User

def index(request): #signing IN page
    form = SignInForm(request.POST)
    if request.method == "POST":
        if form.is_valid():
            name = request.POST.get("name")
            password = request.POST["password"]
            user = authenticate(request, username = name, password = password)
            if user is not None:
                login(request,user)
                return redirect('scheduleapp:index')
            else:
                messages.error(request,"Invalid user! Check if the username and/or password is correct." )
                return render(request, "accounts/signin.html", {
                'form':form
            })
    context = {'form':form}
    return render(request, 'accounts/signin.html', context)

def signup(request): #CREATING AN ACCOUNT
    form = SignUpForm(request.POST)
    if request.method == "POST":
        name = request.POST["name"]
        password = request.POST["password"]
        confirmPassword = request.POST["confirmPassword"]
        if confirmPassword != password:
            messages.error(request, "Passwords should match")
            return render(request, "accounts/signup.html", {"msg" : "Passwords should match.", 'form':form})
        else:
            if User.objects.filter(username = name):
                messages.error(request, "This name already taken. Please, choose another one.")
                return render(request, "accounts/signup.html", {'form':form})
            else:
                messages.success(request, "Congratulations, you have created the account successfully!")
                user = User.objects.create_user(username = name, password = password)
                user.save()
                return HttpResponseRedirect(reverse("accounts:index"))
    context = {'form':form}
    return render(request, "accounts/signup.html", context)  

def signout(request):
    logout(request)
    return redirect("accounts:index")

app/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.views import generic
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib import messages

from .models import User, Students, Lesson, DaysOfWeek

@login_required(login_url="accounts:index")
def index(request):
    return render(request, 'app/index.html')    

@login_required(login_url="accounts:index")
def calendar(request):
    pass

@login_required(login_url="accounts:index")
def profile(request):
    return render(request, "app/profile.html")

@login_required(login_url="accounts:index")
def about(request):
    return render(request, "app/about.html")

def addingMenu(request):
    return render(request, "app/adding.html")

#adding students
def addStudent(request):
    if request.method == "POST":
        year = request.POST["year"]
        faculty = request.POST["faculty"]
        number = request.POST["group_number"]
        if Students.objects.filter(group_year = year, group_title = faculty, group_number = number).exists():
            messages.error(request,"This group already exists.")
        else:
            f = Students(group_year = year, group_title = faculty, group_number = number)
            f.save()
    return render(request, "app/AddingForms/addStudents.html")

def deleteStudent(request, year_id):
    relevant_student = Students.objects.get(id = year_id)
    if request.method == "POST":
        Students.objects.filter(id = year_id).delete()
    return HttpResponseRedirect(reverse("scheduleapp:viewStudents", kwargs={"year_id":relevant_student.group_year}))

#viewing
def viewStudents(request, year_id):
    #mh,tmuh, telecom, art
    arr = Students.objects.filter(group_year = year_id).order_by("group_title")
    context = {'students':arr,}
    return render(request, "app/AddingForms/Studentslist.html", context)

def addLesson(request):
    days = DaysOfWeek.objects.all()
    if request.method == "POST":
        lesson_title = request.POST["title_lesson"]
        teacher = request.POST.get("teacher")
        # cabinet = request.POST.get("cab_number")
        # time = request.POST["les_time"]
        # day = request.POST["select-day"]
        user = User.objects.get(id = teacher)
        if Lesson.objects.filter(title = lesson_title ,teacher = user).exists():
            messages.error("This lesson already exists!")
        else:
            f = Lesson(title = lesson_title ,teacher = user)
            f.save()
    context = {"days":days, "teachers":User.objects.all()}
    return render(request, "app/AddingForms/addLesson.html", context)

def addTeacher(request):
    context = {}
    return render(request, "app/AddingForms/addTeacher.html")

def search(request):
    pass

accounts/templates/accounts/signin.html
<!DOCTYPE html>
<html lang="en">
	{% load static %}
    <head>
        <title>Sign In | Event Calendar</title>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />

        <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap" rel="stylesheet" />

        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" />

        <link rel="stylesheet" href="{% static 'css/accounts.css' %}" />
    </head>
    <body>
        <section class="ftco-section">
            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-md-12">
                        <div class="wrap d-md-flex">
                            <div class="text-wrap p-4 p-lg-5 d-flex img" style="background-image: url({% static 'images/bg.jpg' %});">
                                <div class="text w-100">
                                    <h2 class="mb-4">Welcome to Schedule Calendar</h2>
                                    <p>In the land far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.</p>
                                </div>
                            </div>
                            <div class="login-wrap p-4 p-md-5">
                                <div class="row justify-content-center py-md-5">
                                    <div class="col-lg-9">
                                        <div class="social-wrap">
                                            {% if messages %}
                                            {% for i in messages %}
                                            {{i}}
                                            {% endfor %}
                                            {% endif %}
                                            <h3 class="mb-3 text-center">Welcome! Please, login into your account or create one</h3>
                                            <p class="or">
                                                <span>or</span>
                                            </p>
                                        </div>
                                        {% if request.user.is_authenticated %}
                                        <h2 class = "mb-3 text-center logged">You are already logged in!</h2>
                                        {% else %}
                                        <form action="{% url 'accounts:index' %}" method="post" class="signup-form" name = >
                                            {% csrf_token %}
                                            <div class="row">
                                                <div class="col-md-12">
                                                    <div class="form-group">
                                                            {% csrf_token %}
                                                            {{form.as_p}}
                                                            <button type="submit" class="btn btn-primary">Sign In</button>
                                                    </div>
                                                </div>
                                            </div>
                                        </form>
                                        

                                        <div class="w-100">
                                            <p class="mt-4">Don't have an account yet? <a href="{% url 'accounts:signup' %}">Sign Up</a></p>
                                        </div>
                                        {% endif %}
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        {% include 'base/js.html' %}
    </body>
</html>

accounts/templates/accounts/signup.html
<!DOCTYPE html>
<html lang="en">
	{% load static %}
    <head>
        <title>Sign Up | Event Calendar</title>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />

        <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap" rel="stylesheet" />

        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" />

        <link rel="stylesheet" href="{% static 'css/accounts.css' %}" />
    </head>
    <body>
        <section class="ftco-section">
            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-md-12">
                        <div class="wrap d-md-flex">
                            <div class="text-wrap p-4 p-lg-5 d-flex img" style="background-image: url({% static 'images/bg.jpg' %});">
                                <div class="text w-100">
                                    <h2 class="mb-4">Welcome to Event Calendar</h2>
                                    <p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.</p>
                                </div>
                            </div>
                            <div class="login-wrap p-4 p-md-5">
                                <div class="row justify-content-center py-md-5">
                                    <div class="col-lg-9">
                                        <div class="social-wrap">
                                            {% if messages %}
                                            {% for i in messages %}
                                            {{i}}
                                            {% endfor %}
                                            {% endif %}
                                            <h3 class="mb-3 text-center">Welcome! You are creating <br>an account!</h3>
                                            <p class="or">
                                                <span>Have a good day!</span>
                                            </p>
                                        </div>
                        
                                        <form action="{%url 'accounts:signup' %}" method="post" class="signup-form">
                                            {% csrf_token %}
                                            {{form.as_p}}
                                            <div class="row">
                                                <div class="col-md-12">
                                                    <div class="form-group">
                                                        <button type="submit" class="btn btn-primary">Create an account</button>
                                                    </div>
                                                </div>
                                            </div>
                                        </form>
                                        <div class="w-100">
                                            <p class="mt-4">I'm already a member! <a href="{% url 'accounts:index' %}">Sign In</a></p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        {% include 'base/js.html' %}
    </body>
</html>

app/templates/app/AddingForms/Studentslist.html
{% extends 'app/layout.html' %}

{% block body %}
<table class="table table-striped">
    <thead>
      <tr>
        <th scope="col">Group Year</th>
        <th scope="col">Faculty</th>
        <th scope="col">Group Number</th>
        <th scope = "col">Remove</th>
      </tr>
    </thead>
{% for student in students %}
    <tbody>
      <tr>
        <th scope="row">{{student.group_year}}</th>
        <td>{{student.group_title}}</td>
        <td>{{student.group_number}}</td>
        <td><form action = "{% url 'scheduleapp:deleteStudent' student.id%}" method = "post">{% csrf_token %}<button type="submit" class="btn btn-danger" name = "delete">Remove</button></form></td>
      </tr>
    </tbody>
{% endfor %}
</table>

{% endblock body %}

app/templates/app/AddingForms/addLesson.html
{% extends 'app/layout.html' %}

{% block body %}
<h1>You Are Adding A New Lesson. <br>Please, fill in this form.</h1>
{% if messages %}
    {% for i in messages %}
        {{i}}
    {% endfor %}
{% endif %}
<form action = "{% url 'scheduleapp:addLesson' %}" method = "post" class = "was-validated">
  {% csrf_token %}
    <div class="mb-3">
      <label for="title_lesson" class="form-label">Title of a lesson</label>
      <input type="text" class="form-control is-invalid" name = "title_lesson" id="title_lesson" required>
      <label for="teacher" class="form-label">Choose the Teacher</label>
      <select class="form-select form-control" id="teacher" aria-describedby="validationServer04Feedback" name = "teacher" required>
        <option value="" disabled selected>Who is the teacher?</option>
        {% for teacher in teachers %}
            <option value="{{teacher.id}}">{{teacher}}</option>
        {% endfor %}

      </select>
      {% comment %} <label for="cab_number" class="form-label">Where it's teached?</label>
      <input type="number" class="form-control is-invalid" name = "cab_nubmer" id="cab_nubmer" required>
      <label for="day" class="form-label">When it's teached?</label>
      <select class="form-select form-control " id="select-day" aria-describedby="validationServer04Feedback" name = "select-day" required>
        <option value="" selected disabled>Choose the day</option>
        {% for day in days %}
            <option value="{{day.id}}">{{day.name}}</option>
        {% endfor %}
      </select>
      <label for="les_time" class="form-label">Time of the lesson?</label>
      <input type="time" class="form-control is-valid" name = "les_time" id = "les_time" required> {% endcomment %}
    </div>
    <button type="submit" class="btn btn-primary">Add</button>
  </form>
{% endblock body %}

app/templates/app/AddingForms/addStudents.html
{% extends 'app/layout.html' %}

{% block body %}
<h1>You Are Adding A New Students. <br>Please, fill in this form.</h1>
{% if messages %}
    {% for i in messages %}
        {{i}}
    {% endfor %}
{% endif %}
<form action = "{% url 'scheduleapp:addStudent' %}" method = "post" class = "was-validated">
  {% csrf_token %}
    <div class="mb-3">
      <label for="year" class="form-label">Year of a students</label>
      <input type="number" class="form-control is-invalid" name = "year" id="year" required>
      <label for="faculty" class="form-label">Faculty</label>
      <input type="text" class="form-control is-valid" name = "faculty" id = "faculty" required>
      <label for="num" class="form-label">Group's Number</label>
      <input type="number" class="form-control is-valid" name = "group_number" id = "num" required>
    </div>
    <button type="submit" class="btn btn-primary">Add</button>
  </form>
  <ul class="list-group">
    <li class="list-group-item active" aria-current="true">Active Years:</li>
    <nav class="navbar navbar-light bg-light">
        <span class="navbar-brand mb-0 h1 link-secondary">Select</span>
        <a href="{% url 'scheduleapp:viewStudents' 1%}"><button href="{% url 'scheduleapp:viewStudents' 1%}" class="btn btn-primary" name = "1">1 Year</button></a>
        <a href="{% url 'scheduleapp:viewStudents' 2%}"><button href="{% url 'scheduleapp:viewStudents' 2%}" class="btn btn-primary" name = "2">2 Year</button></a>
        <a href="{% url 'scheduleapp:viewStudents' 3%}"><button href="{% url 'scheduleapp:viewStudents' 3%}" class="btn btn-primary" name = "3">3 Year</button></a>
        <a href="{% url 'scheduleapp:viewStudents' 4%}"><button href="{% url 'scheduleapp:viewStudents' 4%}" class="btn btn-primary" name = "4">4 Year</button></a>
        <a href="{% url 'scheduleapp:viewStudents' 5%}"><button href="{% url 'scheduleapp:viewStudents' 5%}" class="btn btn-primary" name = "5">5 Year</button></a>

    </nav>
  </ul> 
{% endblock body %}

app/templates/app/AddingForms/addTeacher.html
{% extends 'app/layout.html' %}

{% block body %}
adding teacher
{% endblock body %}

app/templates/app/about.html
{% extends 'app/layout.html' %}

{% block body %}
<h1>Information about the app</h1>
<p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. 
    Delectus iusto voluptatem magnam natus quibusdam ipsam deserunt 
    cum debitis repellendus sequi praesentium voluptate recusandae quas nisi temporibus 
    vero sunt, molestiae, illo enim a eos ad distinctio aspernatur. 
    Porro necessitatibus asperiores consequatur atque. 
    Sapiente similique ab odit nulla laboriosam modi quisquam culpa!</p>
{% endblock body %}

app/templates/app/adding.html
{% extends 'app/layout.html' %}

{% block body %}
<h1>Adding some information</h1>
<nav class="navbar navbar-light bg-light">
    <span class="navbar-brand mb-0 h1 link-secondary">Add</span>
    <a href="{% url 'scheduleapp:addStudent' %}"><button href="{% url 'scheduleapp:addStudent'%}" class="btn btn-primary">A New Students</button></a>
    <a href="{% url 'scheduleapp:addLesson' %}"><button href="{% url 'scheduleapp:addLesson'%}" class="btn btn-primary">A New Lesson</button></a>
    <a href="{% url 'scheduleapp:addTeacher' %}"><button href="{% url 'scheduleapp:addTeacher'%}" class="btn btn-primary">A New Teacher</button></a>
</nav>
{% endblock body %}

app/templates/app/index.html
{% extends 'app/layout.html' %}
{% block body %}
<h1>Hello from the States Of Farland!</h1>
<h2>This is auto-generating schedule app that will make your life much easier!</h2>
<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Laborum modi doloribus mollitia recusandae, excepturi placeat, maxime ex tenetur accusantium libero sapiente labore quisquam qui omnis incidunt tempora quo enim! Hic dolorum itaque, qui voluptatum possimus maiores praesentium eligendi eaque ea. Sapiente, error eum debitis, quasi velit quia perspiciatis pariatur dicta distinctio odio suscipit, neque rerum. Dolor error incidunt perferendis hic, deleniti aspernatur iste modi maiores laudantium corporis cupiditate esse exercitationem atque in pariatur officiis provident libero labore voluptatum eaque est expedita. Delectus, consequuntur rerum atque repellendus dignissimos ipsa laudantium officia reiciendis itaque explicabo voluptatum animi cum voluptas, assumenda doloribus. Sed.</p>
{% endblock body %}

app/templates/app/layout.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
  	<title>Schedule</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="shortcut icon" href="{% static 'images/ben-o-bro-wpU4veNGnHg-unsplash.jpg' %}" type="image/x-icon">
    <link href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700,800,900" rel="stylesheet">
		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
		<link rel="stylesheet" href="{% static 'css/style.css' %}">
  </head>
  <body>
		<div class="wrapper d-flex align-items-stretch">
			<nav id="sidebar" class="active">
				<h1><a href="index.html" class="logo">%/$</a></h1>
        <ul class="list-unstyled components mb-5">
          <li class="active">
            <a href="{% url 'scheduleapp:index' %}"><span class="fa fa-home"></span> Home</a>
          </li>
          <li>
              <a href="{% url 'scheduleapp:about' %}"><span class="fa fa-user"></span> About</a>
          </li>
          <li>
            <a href="{% url 'scheduleapp:adding' %}"><span class="fa fa-sticky-note"></span> Add</a>
          </li>
          <li>
            <a href="#"><span class="fa fa-cogs"></span> Services</a>
          </li>
          <li>
            <a href="{%url 'accounts:signout' %}"><span class="fa fa-paper-plane"></span> Log out</a>
          </li>
        </ul>
        <div class="footer">
        	<p>
					  Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="icon-heart" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib.com</a>
					</p>
        </div>
    	</nav>

        <!-- Page Content  -->
      <div id="content" class="p-4 p-md-5">

        <nav class="navbar navbar-expand-lg navbar-light bg-light">
          <div class="container-fluid">
            <button class="btn btn-dark d-inline-block d-lg-none ml-auto" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <i class="fa fa-bars"></i>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
              <ul class="nav navbar-nav ml-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'scheduleapp:index' %}">Home</a>
                </li>
                <li  class="nav-item active">
                    <a class="nav-link" href="#">Portfolio</a>
                </li>
                <li  class="nav-item active" >
                  <a href="scheduleapp:about" class = "nav-link">About</a>
                </li>
                <li  class="nav-item active" >
                  <a href="{%url 'accounts:signout' %}" class = "nav-link ">Log out</a>
                </li>
              </ul>
            </div>
          </div>
        </nav>
		{% block body %}{% endblock body %}

      </div>
		</div>
    <script src="{% static 'js/jquery.min.js'%}"></script>
    <script src="{% static 'js/popper.js'%}"></script>
    <script src="{% static 'js/bootstrap.min.js'%}"></script>
    <script src="{% static 'js/main.js' %}"></script>
  </body>
</html>

app/templates/app/profile.html
{% extends 'app/layout.html' %}

{% block body %}

{% endblock body %}

app/templates/base/js.html
{% load static %}
<script src="{% static 'js/js/jquery-3.3.1.min.js' %}"></script>
<script src="{% static 'js/popper.js' %}"></script>
<script src="{% static 'js/js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/main.js' %}"></script>
<!-- The javascript plugin to display page loading on top-->
<script src="{% static 'js/plugins/pace.min.js'%}"></script>